### ISSUE TITLE
Bugs is newly pushed files

### ISSUE THREAD

**Issue by shrawankc11** [shrawankc11/Salary-Tax-Calculator#5]
Recent push from prajeet has created some issues please solve fix them bugs.

**Comment by Prajeet111** [comment]
Fixed the bug please close the issue.

**Comment by ManiKarke10** [comment]
Fix the bug please close the issue

**Comment by shrawankc11** [comment]
#5. This issue has been solved after removing the merge conflict 87dd6ad628beb33d287d6bf76398ffb49d292f41
