### ISSUE TITLE
Error in JavaScript

### ISSUE THREAD

**Issue by shrawankc11** [shrawankc11/Salary-Tax-Calculator#6]
There has been an error in the js file. Hence, it is inaccurate. Please go through the taxes calculation and fix the bug.

**Comment by ManiKarke10** [comment]
Fix conflict

**Comment by shrawankc11** [comment]
#6. I fixed the calculator not working part. Issue tracked and solves! e825c59dfb54f94338fc418fe821a237eabe55cb

**Comment by shrawankc11** [comment]
Solves the issue check in commit : e825c59dfb54f94338fc418fe821a237eabe55cb
